"""Datos del catálogo de formas musicales — importado por structure_catalog."""

from __future__ import annotations

from typing import TypedDict


class StructureFormSpec(TypedDict):
    sections: list[str]
    description: str
    use_cases: list[str]
    genre_hints: list[str]
    energy_range: tuple[int, int]
    duration_sec: tuple[int, int]
    default_bars: dict[str, int]


STRUCTURE_FORMS: dict[str, StructureFormSpec] = {
    # --- Boss y combate ---
    "boss_edm": {
        "sections": ["intro", "build-up", "drop", "outro"],
        "description": "Boss EDM/dubstep: tensión → drop → cierre",
        "use_cases": ["game", "animation"],
        "genre_hints": [
            "techno", "dubstep", "brostep", "drum and bass", "boss fight",
            "industrial techno", "hardstyle",
        ],
        "energy_range": (4, 5),
        "duration_sec": (45, 90),
        "default_bars": {"intro": 8, "build-up": 16, "drop": 16, "outro": 8},
    },
    "boss_orchestral": {
        "sections": [
            "intro", "verse", "pre-chorus", "main-theme", "bridge", "climax", "outro",
        ],
        "description": "Boss orquestal épico: desarrollo largo y clímax cinematográfico",
        "use_cases": ["game", "animation"],
        "genre_hints": [
            "orchestral", "cinematic", "epic", "symphonic", "boss fight",
            "hybrid orchestral", "trailer music",
        ],
        "energy_range": (4, 5),
        "duration_sec": (60, 120),
        "default_bars": {
            "intro": 8, "verse": 12, "pre-chorus": 8, "main-theme": 16,
            "bridge": 8, "climax": 16, "outro": 8,
        },
    },
    "boss_extended": {
        "sections": ["intro", "build-up", "drop", "bridge", "outro"],
        "description": "Boss con puente tras el drop (rock/metal/orquestal)",
        "use_cases": ["game"],
        "genre_hints": ["boss fight", "metal", "rock", "orchestral"],
        "energy_range": (3, 5),
        "duration_sec": (50, 100),
        "default_bars": {"intro": 8, "build-up": 12, "drop": 16, "bridge": 8, "outro": 8},
    },
    "boss_dnb": {
        "sections": ["intro", "build-up", "drop", "breakdown", "bridge", "climax", "outro"],
        "description": "Boss drum & bass: drop rápido, breakdown y segundo pico",
        "use_cases": ["game", "animation"],
        "genre_hints": ["drum and bass", "dnb", "jungle", "boss fight", "breakcore"],
        "energy_range": (4, 5),
        "duration_sec": (50, 95),
        "default_bars": {
            "intro": 8, "build-up": 12, "drop": 12, "breakdown": 8,
            "bridge": 8, "climax": 12, "outro": 8,
        },
    },
    "boss_dubstep": {
        "sections": ["intro", "build-up", "drop", "breakdown", "climax", "outro"],
        "description": "Boss dubstep/brostep: wobble, breakdown y clímax final",
        "use_cases": ["game"],
        "genre_hints": ["dubstep", "brostep", "riddim", "boss fight", "bass music"],
        "energy_range": (4, 5),
        "duration_sec": (48, 90),
        "default_bars": {
            "intro": 8, "build-up": 16, "drop": 16, "breakdown": 8, "climax": 12, "outro": 8,
        },
    },
    "boss_metal": {
        "sections": ["intro", "verse", "breakdown", "climax", "outro"],
        "description": "Boss metal: riff, breakdown pesado y clímax",
        "use_cases": ["game"],
        "genre_hints": ["metal", "metalcore", "djent", "boss fight", "heavy"],
        "energy_range": (4, 5),
        "duration_sec": (45, 85),
        "default_bars": {"intro": 8, "verse": 12, "breakdown": 12, "climax": 16, "outro": 8},
    },
    "boss_chiptune": {
        "sections": ["intro", "verse", "chorus", "bridge", "climax", "outro"],
        "description": "Boss 8-bit/chiptune: melodía pegadiza y clímax arcade",
        "use_cases": ["game"],
        "genre_hints": ["chiptune", "8-bit", "nes", "boss fight", "arcade"],
        "energy_range": (4, 5),
        "duration_sec": (40, 75),
        "default_bars": {
            "intro": 4, "verse": 8, "chorus": 8, "bridge": 8, "climax": 12, "outro": 4,
        },
    },
    "boss_hybrid": {
        "sections": ["intro", "verse", "build-up", "drop", "climax", "outro"],
        "description": "Boss híbrido orquestal+EDM: tema → build → drop → clímax",
        "use_cases": ["game", "animation"],
        "genre_hints": [
            "hybrid orchestral", "epic", "edm", "cinematic", "boss fight", "trailer",
        ],
        "energy_range": (4, 5),
        "duration_sec": (55, 100),
        "default_bars": {
            "intro": 8, "verse": 12, "build-up": 12, "drop": 12, "climax": 12, "outro": 8,
        },
    },
    "boss_multi_phase": {
        "sections": ["intro", "build-up", "drop", "bridge", "climax", "outro"],
        "description": "Boss por fases: primer pico, puente y clímax final",
        "use_cases": ["game"],
        "genre_hints": ["boss fight", "phases", "raid", "final boss"],
        "energy_range": (4, 5),
        "duration_sec": (60, 110),
        "default_bars": {
            "intro": 8, "build-up": 12, "drop": 12, "bridge": 8, "climax": 16, "outro": 8,
        },
    },
    "game_standard": {
        "sections": ["intro", "build-up", "drop", "outro"],
        "description": "Combate/nivel estándar sin forma pop",
        "use_cases": ["game"],
        "genre_hints": ["video game music", "game", "action", "combat"],
        "energy_range": (3, 5),
        "duration_sec": (36, 72),
        "default_bars": {"intro": 8, "build-up": 12, "drop": 12, "outro": 8},
    },
    "combat_intense": {
        "sections": ["intro", "build-up", "drop", "climax", "outro"],
        "description": "Combate intenso: subida rápida y doble pico energético",
        "use_cases": ["game"],
        "genre_hints": ["action", "combat", "shooter", "arena", "intense"],
        "energy_range": (4, 5),
        "duration_sec": (32, 65),
        "default_bars": {"intro": 4, "build-up": 12, "drop": 12, "climax": 12, "outro": 4},
    },
    "combat_raid": {
        "sections": ["intro", "build-up", "drop", "bridge", "climax", "outro"],
        "description": "Raid/misión cooperativa: tensión larga y clímax grupal",
        "use_cases": ["game"],
        "genre_hints": ["raid", "co-op", "mmorpg", "elite", "combat"],
        "energy_range": (3, 5),
        "duration_sec": (50, 90),
        "default_bars": {
            "intro": 8, "build-up": 16, "drop": 12, "bridge": 8, "climax": 12, "outro": 8,
        },
    },
    "combat_survival": {
        "sections": ["intro", "verse", "build-up", "drop", "breakdown", "outro_loop"],
        "description": "Supervivencia/horde: oleadas con respiro breve",
        "use_cases": ["game"],
        "genre_hints": ["survival", "horde", "zombie", "wave", "endless"],
        "energy_range": (3, 5),
        "duration_sec": (40, 80),
        "default_bars": {
            "intro": 8, "verse": 8, "build-up": 12, "drop": 12, "breakdown": 8, "outro_loop": 4,
        },
    },
    "pre_battle": {
        "sections": ["intro", "tension_swell", "build-up", "outro"],
        "description": "Pre-batalla: tensión sin drop completo (transición a combate)",
        "use_cases": ["game", "cutscene"],
        "genre_hints": ["pre-battle", "tension", "approach", "warning"],
        "energy_range": (2, 4),
        "duration_sec": (20, 40),
        "default_bars": {"intro": 4, "tension_swell": 12, "build-up": 12, "outro": 4},
    },
    "wave_combat": {
        "sections": ["intro", "verse", "build-up", "drop", "outro"],
        "description": "Oleadas de enemigos: tema estable + picos repetibles",
        "use_cases": ["game"],
        "genre_hints": ["wave", "arena", "tower defense", "combat"],
        "energy_range": (3, 5),
        "duration_sec": (36, 70),
        "default_bars": {"intro": 8, "verse": 8, "build-up": 12, "drop": 12, "outro": 8},
    },
    # --- EDM y electrónica ---
    "edm_double_drop": {
        "sections": ["intro", "build-up", "drop", "breakdown", "bridge", "climax", "outro"],
        "description": "EDM doble drop: primer drop, breakdown y segundo pico",
        "use_cases": ["game", "animation"],
        "genre_hints": ["edm", "festival", "big room", "electro house", "drop"],
        "energy_range": (4, 5),
        "duration_sec": (55, 100),
        "default_bars": {
            "intro": 8, "build-up": 12, "drop": 12, "breakdown": 8,
            "bridge": 8, "climax": 16, "outro": 8,
        },
    },
    "edm_melodic": {
        "sections": ["intro", "verse", "build-up", "drop", "outro"],
        "description": "EDM melódico: estribillo vocal/sintético antes del drop",
        "use_cases": ["game", "animation"],
        "genre_hints": ["melodic dubstep", "future bass", "edm", "electropop"],
        "energy_range": (3, 5),
        "duration_sec": (40, 80),
        "default_bars": {"intro": 8, "verse": 12, "build-up": 12, "drop": 12, "outro": 8},
    },
    "trance_journey": {
        "sections": ["intro", "build-up", "climax", "breakdown", "bridge", "outro"],
        "description": "Trance/progressive: viaje largo con breakdown emotivo",
        "use_cases": ["game", "animation"],
        "genre_hints": ["trance", "progressive trance", "uplifting", "psytrance"],
        "energy_range": (3, 5),
        "duration_sec": (50, 95),
        "default_bars": {
            "intro": 8, "build-up": 16, "climax": 16, "breakdown": 8, "bridge": 8, "outro": 8,
        },
    },
    "house_groove": {
        "sections": ["intro", "verse", "chorus", "outro_loop"],
        "description": "House/deep house: groove estable para loop de pista",
        "use_cases": ["game", "loop"],
        "genre_hints": ["house", "deep house", "disco", "funk house"],
        "energy_range": (2, 4),
        "duration_sec": (32, 64),
        "default_bars": {"intro": 8, "verse": 12, "chorus": 12, "outro_loop": 4},
    },
    "hardstyle_peak": {
        "sections": ["intro", "build-up", "climax", "outro"],
        "description": "Hardstyle: kick distorsionado y clímax en off-beat",
        "use_cases": ["game"],
        "genre_hints": ["hardstyle", "rawstyle", "hard dance", "festival"],
        "energy_range": (4, 5),
        "duration_sec": (36, 70),
        "default_bars": {"intro": 8, "build-up": 16, "climax": 16, "outro": 8},
    },
    "synthwave_arc": {
        "sections": ["intro", "verse", "chorus", "bridge", "outro"],
        "description": "Synthwave/retrowave: nostálgico con puente atmosférico",
        "use_cases": ["game", "loop"],
        "genre_hints": ["synthwave", "retrowave", "outrun", "80s", "neon"],
        "energy_range": (2, 4),
        "duration_sec": (36, 72),
        "default_bars": {"intro": 8, "verse": 12, "chorus": 12, "bridge": 8, "outro": 8},
    },
    "techno_minimal": {
        "sections": ["intro", "pad_layering", "build-up", "drop", "outro"],
        "description": "Techno minimal: capas hipnóticas y drop seco",
        "use_cases": ["game", "loop"],
        "genre_hints": ["techno", "minimal techno", "industrial", "berlin"],
        "energy_range": (3, 5),
        "duration_sec": (40, 80),
        "default_bars": {
            "intro": 8, "pad_layering": 12, "build-up": 12, "drop": 12, "outro": 8,
        },
    },
    "dnb_roller": {
        "sections": ["intro", "verse", "drop", "breakdown", "outro"],
        "description": "DnB rodante: groove constante con drop y respiro",
        "use_cases": ["game", "loop"],
        "genre_hints": ["drum and bass", "liquid dnb", "roller", "jungle"],
        "energy_range": (3, 5),
        "duration_sec": (36, 72),
        "default_bars": {"intro": 8, "verse": 12, "drop": 12, "breakdown": 8, "outro": 8},
    },
    # --- Loops y exploración ---
    "loop_ambient": {
        "sections": ["intro", "pad_layering", "melodic_motif", "outro_loop"],
        "description": "Loop exploración: capas estables, sin clímax de combate",
        "use_cases": ["loop"],
        "genre_hints": ["ambient", "loop", "chillout", "overworld", "pad"],
        "energy_range": (1, 3),
        "duration_sec": (24, 60),
        "default_bars": {
            "intro": 4, "pad_layering": 12, "melodic_motif": 12, "outro_loop": 4,
        },
    },
    "loop_exploration": {
        "sections": ["intro", "exploration_bed", "melodic_motif", "outro_loop"],
        "description": "Exploración aventurera: motivo melódico sobre base ligera",
        "use_cases": ["loop"],
        "genre_hints": ["exploration", "overworld", "adventure", "field", "rpg"],
        "energy_range": (2, 3),
        "duration_sec": (28, 56),
        "default_bars": {
            "intro": 4, "exploration_bed": 12, "melodic_motif": 12, "outro_loop": 4,
        },
    },
    "loop_dungeon": {
        "sections": ["intro", "dungeon_bed", "tension_swell", "outro_loop"],
        "description": "Mazmorra oscura: tensión baja-media, sin clímax EDM",
        "use_cases": ["loop"],
        "genre_hints": ["dungeon", "cave", "dark", "underground", "crypt"],
        "energy_range": (2, 4),
        "duration_sec": (28, 56),
        "default_bars": {
            "intro": 4, "dungeon_bed": 12, "tension_swell": 8, "outro_loop": 4,
        },
    },
    "loop_town": {
        "sections": ["intro", "verse", "chorus", "outro_loop"],
        "description": "Pueblo/ciudad segura: tema cálido y repetible",
        "use_cases": ["loop"],
        "genre_hints": ["town", "village", "hub", "safe zone", "cozy"],
        "energy_range": (1, 3),
        "duration_sec": (28, 56),
        "default_bars": {"intro": 4, "verse": 12, "chorus": 12, "outro_loop": 4},
    },
    "loop_underwater": {
        "sections": ["intro", "pad_layering", "melodic_motif", "outro_loop"],
        "description": "Bajo el agua: filtrado, pads amplios y movimiento lento",
        "use_cases": ["loop"],
        "genre_hints": ["underwater", "aquatic", "swim", "submerged", "ambient"],
        "energy_range": (1, 3),
        "duration_sec": (24, 52),
        "default_bars": {
            "intro": 4, "pad_layering": 12, "melodic_motif": 12, "outro_loop": 4,
        },
    },
    "loop_stealth": {
        "sections": ["intro", "stealth_bed", "outro_loop"],
        "description": "Sigilo: textura mínima, sin picos dramáticos",
        "use_cases": ["loop", "game"],
        "genre_hints": ["stealth", "sneak", "infiltration", "spy", "quiet"],
        "energy_range": (1, 2),
        "duration_sec": (20, 48),
        "default_bars": {"intro": 4, "stealth_bed": 16, "outro_loop": 4},
    },
    "loop_travel": {
        "sections": ["intro", "verse", "bridge", "outro_loop"],
        "description": "Viaje/montura: ritmo constante con variación en puente",
        "use_cases": ["loop"],
        "genre_hints": ["travel", "journey", "road", "flying", "mount"],
        "energy_range": (2, 3),
        "duration_sec": (28, 56),
        "default_bars": {"intro": 4, "verse": 12, "bridge": 8, "outro_loop": 4},
    },
    "loop_survival": {
        "sections": ["intro", "verse", "build-up", "breakdown", "outro_loop"],
        "description": "Supervivencia en mundo abierto: tensión cíclica moderada",
        "use_cases": ["loop", "game"],
        "genre_hints": ["survival", "crafting", "open world", "resource"],
        "energy_range": (2, 4),
        "duration_sec": (32, 60),
        "default_bars": {
            "intro": 4, "verse": 12, "build-up": 8, "breakdown": 8, "outro_loop": 4,
        },
    },
    # --- Cutscene y cinemática ---
    "cutscene_arc": {
        "sections": ["intro", "dialogue_bed", "tension_swell", "outro"],
        "description": "Cutscene: diálogo → tensión → resolución",
        "use_cases": ["cutscene"],
        "genre_hints": ["cutscene", "cinematic", "ambient", "dialogue"],
        "energy_range": (1, 3),
        "duration_sec": (20, 45),
        "default_bars": {
            "intro": 4, "dialogue_bed": 12, "tension_swell": 8, "outro": 4,
        },
    },
    "cutscene_reveal": {
        "sections": ["intro", "dialogue_bed", "tension_swell", "climax", "outro"],
        "description": "Revelación/plot twist: diálogo → tensión → golpe dramático",
        "use_cases": ["cutscene", "animation"],
        "genre_hints": ["reveal", "twist", "betrayal", "cinematic", "story"],
        "energy_range": (2, 4),
        "duration_sec": (24, 50),
        "default_bars": {
            "intro": 4, "dialogue_bed": 8, "tension_swell": 8, "climax": 8, "outro": 4,
        },
    },
    "cutscene_emotional": {
        "sections": ["intro", "verse", "bridge", "climax", "outro"],
        "description": "Momento emotivo: desarrollo íntimo y clímax contenido",
        "use_cases": ["cutscene", "animation"],
        "genre_hints": ["emotional", "sad", "farewell", "piano", "strings"],
        "energy_range": (1, 3),
        "duration_sec": (30, 60),
        "default_bars": {"intro": 4, "verse": 12, "bridge": 8, "climax": 8, "outro": 4},
    },
    "cutscene_chase": {
        "sections": ["intro", "chase", "climax", "outro"],
        "description": "Persecución: ritmo urgente y clímax de escape",
        "use_cases": ["cutscene", "game", "animation"],
        "genre_hints": ["chase", "escape", "pursuit", "run", "urgent"],
        "energy_range": (3, 5),
        "duration_sec": (24, 48),
        "default_bars": {"intro": 4, "chase": 12, "climax": 8, "outro": 4},
    },
    "cutscene_horror": {
        "sections": ["intro", "dialogue_bed", "horror_bed", "outro"],
        "description": "Horror narrativo: inquietud sin jump-scare musical",
        "use_cases": ["cutscene"],
        "genre_hints": ["horror", "creepy", "dread", "suspense", "haunted"],
        "energy_range": (1, 3),
        "duration_sec": (20, 42),
        "default_bars": {"intro": 4, "dialogue_bed": 8, "horror_bed": 12, "outro": 4},
    },
    "animation_climax": {
        "sections": ["intro", "build-up", "climax", "outro"],
        "description": "Animación/trailer: subida a clímax sin drop EDM",
        "use_cases": ["animation"],
        "genre_hints": ["cinematic", "animation", "trailer music", "epic"],
        "energy_range": (3, 5),
        "duration_sec": (40, 90),
        "default_bars": {"intro": 8, "build-up": 16, "climax": 16, "outro": 8},
    },
    "trailer_short": {
        "sections": ["intro", "build-up", "climax", "outro"],
        "description": "Trailer corto (~30–45 s): arco comprimido",
        "use_cases": ["animation", "cutscene"],
        "genre_hints": ["trailer", "teaser", "promo", "epic", "cinematic"],
        "energy_range": (3, 5),
        "duration_sec": (28, 48),
        "default_bars": {"intro": 4, "build-up": 12, "climax": 12, "outro": 4},
    },
    "montage_pop": {
        "sections": ["intro", "verse", "pre-chorus", "chorus", "climax", "outro"],
        "description": "Montaje/recap: forma pop con clímax final",
        "use_cases": ["animation", "cutscene"],
        "genre_hints": ["montage", "recap", "highlights", "pop", "uplifting"],
        "energy_range": (3, 5),
        "duration_sec": (45, 85),
        "default_bars": {
            "intro": 4, "verse": 8, "pre-chorus": 8, "chorus": 12, "climax": 8, "outro": 4,
        },
    },
    # --- UI y momentos de juego ---
    "arcade_pop": {
        "sections": ["intro", "verse", "chorus", "outro"],
        "description": "Arcade/chiptune pop corto",
        "use_cases": ["game", "loop"],
        "genre_hints": ["chiptune", "arcade", "eurobeat", "8-bit"],
        "energy_range": (3, 5),
        "duration_sec": (30, 60),
        "default_bars": {"intro": 4, "verse": 8, "chorus": 8, "outro": 4},
    },
    "menu_theme": {
        "sections": ["intro", "menu_theme", "outro_loop"],
        "description": "Menú principal: tema memorable y loop limpio",
        "use_cases": ["loop", "game"],
        "genre_hints": ["menu", "title", "main menu", "lobby", "ui"],
        "energy_range": (1, 3),
        "duration_sec": (24, 48),
        "default_bars": {"intro": 4, "menu_theme": 16, "outro_loop": 4},
    },
    "shop_theme": {
        "sections": ["intro", "shop_bed", "outro_loop"],
        "description": "Tienda/merchant: ambiente amigable y corto",
        "use_cases": ["loop", "game"],
        "genre_hints": ["shop", "merchant", "store", "inn", "vendor"],
        "energy_range": (1, 2),
        "duration_sec": (20, 40),
        "default_bars": {"intro": 4, "shop_bed": 12, "outro_loop": 4},
    },
    "victory_fanfare": {
        "sections": ["intro", "chorus", "outro"],
        "description": "Victoria/logro: fanfarria breve y triunfal",
        "use_cases": ["game", "cutscene"],
        "genre_hints": ["victory", "win", "achievement", "fanfare", "success"],
        "energy_range": (3, 5),
        "duration_sec": (12, 28),
        "default_bars": {"intro": 4, "chorus": 8, "outro": 4},
    },
    "defeat_sting": {
        "sections": ["intro", "defeat_sting", "outro"],
        "description": "Derrota/game over corto: caída emocional rápida",
        "use_cases": ["game", "cutscene"],
        "genre_hints": ["defeat", "lose", "fail", "game over", "death"],
        "energy_range": (1, 3),
        "duration_sec": (8, 22),
        "default_bars": {"intro": 2, "defeat_sting": 6, "outro": 2},
    },
    "level_clear": {
        "sections": ["intro", "chorus", "outro"],
        "description": "Nivel completado: celebración corta",
        "use_cases": ["game"],
        "genre_hints": ["level clear", "stage clear", "complete", "jingle"],
        "energy_range": (3, 5),
        "duration_sec": (10, 25),
        "default_bars": {"intro": 2, "chorus": 8, "outro": 2},
    },
    "game_over": {
        "sections": ["intro", "breakdown", "outro"],
        "description": "Game over: desinflado y cierre sombrío",
        "use_cases": ["game"],
        "genre_hints": ["game over", "continue", "retry", "fail"],
        "energy_range": (1, 3),
        "duration_sec": (12, 30),
        "default_bars": {"intro": 4, "breakdown": 8, "outro": 4},
    },
    "title_screen": {
        "sections": ["intro", "main-theme", "outro"],
        "description": "Pantalla título: tema icónico y cierre suave",
        "use_cases": ["loop", "game"],
        "genre_hints": ["title screen", "attract mode", "logo", "opening"],
        "energy_range": (2, 4),
        "duration_sec": (28, 55),
        "default_bars": {"intro": 8, "main-theme": 16, "outro": 8},
    },
    "credits_roll": {
        "sections": ["intro", "verse", "chorus", "outro"],
        "description": "Créditos finales: rollo emotivo con estribillo",
        "use_cases": ["cutscene", "animation"],
        "genre_hints": ["credits", "ending", "staff roll", "epilogue"],
        "energy_range": (2, 4),
        "duration_sec": (60, 120),
        "default_bars": {"intro": 8, "verse": 16, "chorus": 16, "outro": 8},
    },
    # --- Calma, puzzle y tensión ambiental ---
    "puzzle_calm": {
        "sections": ["intro", "pad_layering", "melodic_motif", "outro_loop"],
        "description": "Puzzle/reflexión: concentración sin distracción",
        "use_cases": ["loop", "game"],
        "genre_hints": ["puzzle", "thinking", "calm", "brain", "logic"],
        "energy_range": (1, 2),
        "duration_sec": (24, 52),
        "default_bars": {
            "intro": 4, "pad_layering": 12, "melodic_motif": 12, "outro_loop": 4,
        },
    },
    "rest_camp": {
        "sections": ["intro", "verse", "melodic_motif", "outro_loop"],
        "description": "Campamento/descanso: recuperación y calma",
        "use_cases": ["loop", "game"],
        "genre_hints": ["rest", "camp", "heal", "save point", "inn"],
        "energy_range": (1, 2),
        "duration_sec": (24, 48),
        "default_bars": {"intro": 4, "verse": 12, "melodic_motif": 8, "outro_loop": 4},
    },
    "horror_ambient": {
        "sections": ["intro", "horror_bed", "tension_swell", "outro_loop"],
        "description": "Horror ambiental: inquietud sostenida para exploración",
        "use_cases": ["loop", "game"],
        "genre_hints": ["horror", "survival horror", "resident evil", "dread"],
        "energy_range": (2, 4),
        "duration_sec": (28, 56),
        "default_bars": {
            "intro": 4, "horror_bed": 12, "tension_swell": 8, "outro_loop": 4,
        },
    },
    "stealth_tension": {
        "sections": ["intro", "stealth_bed", "tension_swell", "outro"],
        "description": "Sigilo con tensión: casi descubierto, sin combate pleno",
        "use_cases": ["game", "loop"],
        "genre_hints": ["stealth", "detection", "alert", "sneak"],
        "energy_range": (2, 4),
        "duration_sec": (28, 52),
        "default_bars": {"intro": 4, "stealth_bed": 12, "tension_swell": 8, "outro": 4},
    },
    # --- Acción y carreras ---
    "racing_high": {
        "sections": ["intro", "build-up", "drop", "outro"],
        "description": "Carreras/deportes: velocidad y pico adrenalínico",
        "use_cases": ["game", "animation"],
        "genre_hints": ["racing", "driving", "sports", "speed", "kart"],
        "energy_range": (4, 5),
        "duration_sec": (32, 65),
        "default_bars": {"intro": 4, "build-up": 12, "drop": 12, "outro": 4},
    },
    "chase_sequence": {
        "sections": ["intro", "chase", "build-up", "climax", "outro"],
        "description": "Secuencia de huida larga: escalada hasta clímax",
        "use_cases": ["game", "animation", "cutscene"],
        "genre_hints": ["chase", "escape", "qte", "timed run"],
        "energy_range": (4, 5),
        "duration_sec": (36, 72),
        "default_bars": {"intro": 4, "chase": 12, "build-up": 12, "climax": 12, "outro": 4},
    },
    # --- Híbridos y pop de juego ---
    "orchestral_edm": {
        "sections": ["intro", "verse", "build-up", "drop", "climax", "outro"],
        "description": "Orquesta + EDM: tema híbrido con drop moderno",
        "use_cases": ["game", "animation"],
        "genre_hints": ["hybrid", "orchestral edm", "two steps from hell", "epic edm"],
        "energy_range": (4, 5),
        "duration_sec": (50, 95),
        "default_bars": {
            "intro": 8, "verse": 12, "build-up": 12, "drop": 12, "climax": 12, "outro": 8,
        },
    },
    "cinematic_action": {
        "sections": ["intro", "build-up", "main-theme", "climax", "outro"],
        "description": "Acción cinematográfica sin drop de club",
        "use_cases": ["game", "animation"],
        "genre_hints": ["action", "cinematic", "blockbuster", "hybrid orchestral"],
        "energy_range": (3, 5),
        "duration_sec": (40, 85),
        "default_bars": {
            "intro": 8, "build-up": 12, "main-theme": 12, "climax": 12, "outro": 8,
        },
    },
    "pop_ballad_game": {
        "sections": ["intro", "verse", "pre-chorus", "chorus", "outro"],
        "description": "Balada/pop emotivo para momentos de personaje",
        "use_cases": ["cutscene", "loop"],
        "genre_hints": ["ballad", "pop", "j-pop", "character theme", "emotional"],
        "energy_range": (2, 4),
        "duration_sec": (36, 72),
        "default_bars": {
            "intro": 4, "verse": 12, "pre-chorus": 8, "chorus": 12, "outro": 4,
        },
    },
    "funk_groove": {
        "sections": ["intro", "verse", "chorus", "bridge", "outro"],
        "description": "Funk/disco groove: ritmo danceable para minijuegos",
        "use_cases": ["game", "loop"],
        "genre_hints": ["funk", "disco", "groove", "dance", "party"],
        "energy_range": (3, 5),
        "duration_sec": (32, 64),
        "default_bars": {"intro": 4, "verse": 12, "chorus": 12, "bridge": 8, "outro": 4},
    },
    "jazz_lounge": {
        "sections": ["intro", "verse", "bridge", "outro_loop"],
        "description": "Jazz/lounge: ambiente sofisticado de bar o casino",
        "use_cases": ["loop", "game"],
        "genre_hints": ["jazz", "lounge", "noir", "casino", "bar"],
        "energy_range": (1, 3),
        "duration_sec": (28, 56),
        "default_bars": {"intro": 4, "verse": 12, "bridge": 8, "outro_loop": 4},
    },
    "emotional_piano": {
        "sections": ["intro", "verse", "bridge", "outro"],
        "description": "Piano/cuerdas íntimo: cutscene o menú emotivo",
        "use_cases": ["cutscene", "loop"],
        "genre_hints": ["piano", "strings", "intimate", "melancholy", "story"],
        "energy_range": (1, 3),
        "duration_sec": (28, 55),
        "default_bars": {"intro": 4, "verse": 12, "bridge": 8, "outro": 4},
    },
}

# Categorías para el prompt del technical_spec (todas las formas deben aparecer en una)
STRUCTURE_FORM_CATEGORIES: dict[str, list[str]] = {
    "boss_combat": [
        "boss_edm", "boss_orchestral", "boss_extended", "boss_dnb", "boss_dubstep",
        "boss_metal", "boss_chiptune", "boss_hybrid", "boss_multi_phase",
        "game_standard", "combat_intense", "combat_raid", "combat_survival",
        "pre_battle", "wave_combat",
    ],
    "edm_electronic": [
        "edm_double_drop", "edm_melodic", "trance_journey", "house_groove",
        "hardstyle_peak", "synthwave_arc", "techno_minimal", "dnb_roller",
    ],
    "loop_exploration": [
        "loop_ambient", "loop_exploration", "loop_dungeon", "loop_town",
        "loop_underwater", "loop_stealth", "loop_travel", "loop_survival",
    ],
    "cutscene_cinematic": [
        "cutscene_arc", "cutscene_reveal", "cutscene_emotional", "cutscene_chase",
        "cutscene_horror", "animation_climax", "trailer_short", "montage_pop",
    ],
    "game_ui": [
        "arcade_pop", "menu_theme", "shop_theme", "victory_fanfare",
        "defeat_sting", "level_clear", "game_over", "title_screen", "credits_roll",
    ],
    "calm_tension": [
        "puzzle_calm", "rest_camp", "horror_ambient", "stealth_tension",
    ],
    "action_racing": ["racing_high", "chase_sequence"],
    "hybrid_styles": [
        "orchestral_edm", "cinematic_action", "pop_ballad_game",
        "funk_groove", "jazz_lounge", "emotional_piano",
    ],
}
